---

- name: Brew service start Gitlab runner
  ansible.builtin.command: brew services start gitlab-runner

- name: Install Gitlab runner
  ansible.builtin.command: gitlab-runner install
  failed_when: false

- name: Start Gitlab runner
  ansible.builtin.command: gitlab-runner start
  failed_when: false

- name: Remove config.toml
  ansible.builtin.file:
    path: ~/.gitlab-runner/config.toml
    state: absent

- name: Register and run Gitlab runners
  ansible.builtin.command:
    argv:
      - gitlab-runner
      - register
      - --non-interactive
      - --url
      - "{{ item.url }}"
      - --registration-token
      - "{{ item.token }}"
      - --executor
      - "{{ item.executor | default('shell') }}"
      - --description
      - "{{ item.name }}"
      - --tag-list
      - "{{ item.taglist | join(',') }}"
      - --locked=false
      - --access-level=not_protected
  loop: "{{ gitlab_runners }}"

# - name: Create Gitlab runner
#   community.general.gitlab_runner:
#     api_url: "{{ gitlabrunner_url }}"
#     api_token: "{{ gitlabrunner_access_token }}"
#     registration_token: "{{ gitlabrunner_registration_token }}"
#     project: "{{ gitlabrunner_project }}"
#     description: "{{ gitlabrunner_description }}"
#     tag_list: "{{ gitlabrunner_taglist }}"
#     state: present
#     active: True
#     run_untagged: False
#     locked: False