---

- name: Check that ~/.gitlab-runner/config.toml exists
  stat:
    path: ~/.gitlab-runner/config.toml
  register: stat_result

- name: Brew service start Gitlab runner
  ansible.builtin.command: brew services start gitlab-runner
  when: not stat_result.stat.exists

- name: Install Gitlab runner
  ansible.builtin.command: gitlab-runner install
  when: not stat_result.stat.exists

- name: Start Gitlab runner
  ansible.builtin.command: gitlab-runner start
  when: not stat_result.stat.exists

- name: Start Gitlab runner
  ansible.builtin.file:
    path: ~/.gitlab-runner/config.toml
    state: absent
  when: stat_result.stat.exists

- name: Register and run Gitlab runner
  ansible.builtin.command:
    argv:
      - gitlab-runner
      - register
      - --non-interactive
      - --url
      - "{{ gitlabrunner_url }}"
      - --registration-token
      - "{{ gitlabrunner_registration_token }}"
      - --executor
      - shell
      - --description
      - "{{ gitlabrunner_description }}"
      - --tag-list
      - macosx
      - --locked=false
      - --access-level=not_protected

# - name: Create Gitlab runner
#   community.general.gitlab_runner:
#     api_url: "{{ gitlabrunner_url }}"
#     api_token: "{{ gitlabrunner_access_token }}"
#     registration_token: "{{ gitlabrunner_registration_token }}"
#     project: "{{ gitlabrunner_project }}"
#     description: "{{ gitlabrunner_description }}"
#     tag_list: "{{ gitlabrunner_taglist }}"
#     state: present
#     active: True
#     run_untagged: False
#     locked: False